name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    - name: Run ETL Phase1
      run: |
        python etl_phase1.py --input data/samples.csv --asv data/asv_table.tsv --images data/images --nc data/env_data.nc --output data/processed --sqlite data/processed/mvp.db
    - name: Run ETL Phase2
      run: |
        python etl_phase2_integration.py --samples data/processed/cleaned_samples.csv --asv data/asv_table.tsv --images data/images --nc data/env_data.nc --output data/processed --sqlite data/processed/mvp.db
    - name: Run tests
      run: |
        pytest -q
    - name: Generate acceptance report
      run: |
        python scripts/generate_acceptance_report.py
    - name: Upload acceptance report
      uses: actions/upload-artifact@v4
      with:
        name: acceptance-report
        path: data/processed/acceptance_report.json
